CREATE TABLE photos (
id INTEGER PRIMARY KEY AUTOINCREMENT,
sha1 TEXT NOT NULL,
fileType TEXT(4) NOT NULL,
origFileName TEXT NOT NULL,
dateTaken TEXT NOT NULL,
dateAdded INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
ts INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX 'photos_sha1_UNIQUE' ON 'photos' ('sha1' ASC);


CREATE TABLE photosets (
id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT NOT NULL,
description TEXT,
ts NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX 'photosets_title_UNIQUE' ON 'photosets' ('title' ASC);

CREATE TABLE galleries (
id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT NOT NULL,
description TEXT,
ts NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX 'galleries_title_UNIQUE' ON 'galleries' ('title' ASC);

CREATE TABLE tags (
id INTEGER PRIMARY KEY AUTOINCREMENT,
tag TEXT,
ts NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX 'tags_tag_UNIQUE' ON 'tags' ('tag' ASC);

CREATE TABLE comments (
id INTEGER PRIMARY KEY AUTOINCREMENT,
comment TEXT,
photo_id INTEGER REFERENCES photos (id),
ts NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE import_meta (
id INTEGER PRIMARY KEY AUTOINCREMENT,
photo_id INTEGER REFERENCES photos (id),
importPath TEXT,
importSource TEXT,
S3 integer,
ts NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX 'import_meta_photo_id_UNIQUE' ON 'import_meta' ('photo_id' ASC);

CREATE TABLE galleries_photosets (
id INTEGER PRIMARY KEY AUTOINCREMENT,
galleries_id INTEGER REFERENCES galleries (id),
photoset_id INTEGER REFERENCES photosets (id),
ts NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX 'galleries_photosets_UNIQUE' ON 'galleries_photosets' ('galleries_id','photoset_id' ASC);

CREATE TABLE tags_photos (
id INTEGER PRIMARY KEY AUTOINCREMENT,
tag_id INTEGER REFERENCES tags (id),
photo_id INTEGER REFERENCES photos (id),
ts NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX 'tags_photos_UNIQUE' ON 'tags_photos' ('tag_id','photo_id' ASC);

CREATE TABLE photosets_photos (
id INTEGER PRIMARY KEY AUTOINCREMENT,
photoset_id INTEGER REFERENCES photos (id),
photo_id INTEGER REFERENCES photosets (id),
ts NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX 'photosets_photos_UNIQUE' ON 'photosets_photos' ('photoset_id','photo_id' ASC);

