CREATE TABLE photos (
id INTEGER PRIMARY KEY AUTOINCREMENT,
sha1 TEXT NOT NULL,
fileType TEXT(4) NOT NULL,
origFileName TEXT NOT NULL,
dateTaken TEXT NOT NULL,
dateAdded INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
ts INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX 'photos_sha1_UNIQUE' ON 'photos' ('sha1' ASC);


CREATE TABLE photosets (
id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT NOT NULL,
ts NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX 'photosets_title_UNIQUE' ON 'photosets' ('title' ASC);

CREATE TABLE galleries (
id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT NOT NULL,
description TEXT,
ts NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX 'galleries_title_UNIQUE' ON 'galleries' ('title' ASC);

CREATE TABLE tags (
id INTEGER PRIMARY KEY AUTOINCREMENT,
tag TEXT,
ts NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX 'tags_tag_UNIQUE' ON 'tags' ('tag' ASC);

CREATE TABLE comments (
id INTEGER PRIMARY KEY AUTOINCREMENT,
comment TEXT,
photo_id INTEGER REFERENCES photos (id),
ts NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE importmeta (
id INTEGER PRIMARY KEY AUTOINCREMENT,
origFileName TEXT,
photo_id INTEGER REFERENCES photos (id),
ts NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE photosets_galleries (
id INTEGER PRIMARY KEY AUTOINCREMENT,
galleries_id INTEGER REFERENCES galleries (id),
photoset_id INTEGER REFERENCES photosets (id),
ts NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tags_photos (
id INTEGER PRIMARY KEY AUTOINCREMENT,
tag_id INTEGER REFERENCES tags (id),
photo_id INTEGER REFERENCES photos (id),
ts NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX 'tags_photos_UNIQUE' ON 'tags_photos' ('tag_id','photo_id' ASC);

CREATE TABLE photosets_photos (
id INTEGER PRIMARY KEY AUTOINCREMENT,
photo_id INTEGER REFERENCES photos (id),
photoset_id INTEGER REFERENCES photosets (id),
ts NOT NULL DEFAULT CURRENT_TIMESTAMP
);


